#!/bin/bash

#SBATCH --nodes=1
#SBATCH --partition franklin
#SBATCH --ntasks-per-node=1 #
#SBATCH --output=myjob_%j.stdout #NAME OF THE OUTPT FILE
#SBATCH --job-name=test #NAME OF YOUR JOB
#SBATCH --export=ALL


#Run desired program here
module load gcc/12.3.0
clear

declare -a srand=(
# [0] = 112
[0]=113
[1]=114
# [2]=115
[2]=116
[3]=117
[4]=118
[5]=119
[6]=120
[7]=121
[8]=122
)

declare -a ranseed1=(
[0]=667720
)

declare -a ranseed2=(
[0]=601210
)

declare -a diff_network1=(
[0]=111111
[1]=111111
[2]=111111
[3]=111111
[4]=111111
[5]=111111
[6]=111111
[7]=111111
[8]=111111
[9]=111111
)

declare -a diff_network2=(
[0]=101111
[1]=111111
[2]=121111
[3]=131111
[4]=141111
[5]=151111
[6]=161111
[7]=171111
[8]=181111
[9]=191111
)

declare -a kappa=(
[0]=1.00E-6
)

declare -a mu_c=(
[0]=1.0
)

declare -a pbond=(
[0]=0.55
)

declare -a num_center=(
[0]=1
)

for  i in ${!srand[@]}; do
        echo ${srand[$i]}
done

for  i in ${!ranseed1[@]}; do
        echo ${ranseed1[$i]} ${ranseed2[$i]}
done

for  i in ${!ranseed1[@]}; do
        echo ${diff_network1[$i]} ${diff_network2[$i]}
done

for  i in ${!mu_c[@]}; do
        echo ${mu_c[$i]}
done

for  i in ${!kappa[@]}; do
        echo ${kappa[$i]}
done

for  i in ${!pbond[@]}; do
        echo ${pbond[$i]}
done

for  i in ${!num_center[@]}; do
        echo ${num_center[$i]}
done


codefname=Movies-Working_2D_Lamel_network_force_cont_dip_bndry_clampled_restlength_circle_inner_fixed_radial_arp_bash_radial.c

outfname=arp_radial_dip_bash_one
#outfname="${outfname}_${counter}.txt"
outfname="${outfname}.txt"

for  s in ${!srand[@]}; do
	for  m in ${!ranseed1[@]}; do
		for  n in ${!diff_network1[@]}; do
			        for  i in ${!kappa[@]}; do
			                for  j in ${!mu_c[@]}; do
			                        for  k in ${!pbond[@]}; do
			                                for  l in ${!num_center[@]}; do
			                                        echo "srand: ${srand[$s]}"
			                                        echo "ranseed1: ${ranseed1[$m]}"
			                                        echo "ranseed2: ${ranseed2[$m]}"
			                                        echo "diff_network1: ${diff_network1[$n]}"
			                                        echo "diff_network2: ${diff_network2[$n]}"
			                                        echo "kappa: ${kappa[$i]}"
			                                        echo "mu_c: ${mu_c[$j]}"
			                                        echo "PBOND: ${pbond[$k]}"
			                                        echo "num_center: ${num_center[$l]}"

			                                        echo "compiling code: $codefname"
			                                        gcc $codefname -Ofast -o lamelrun_1 -m64 nrutil_jen.c -lm -std=c99
			                                        echo "compilation complete"
			                                        echo "executing. outputifile: $outfname"
			                                        #./lamel $paramfile $counter > $outfname
			                                        ./lamelrun_1 ${ranseed1[$m]} ${ranseed2[$m]} ${diff_network1[$n]} ${diff_network2[$n]} ${kappa[$i]} ${mu_c[$j]} ${pbond[$k]} ${num_center[$l]} ${srand[$s]} > $outfname
			                                done
			                        done
			                done
			        done
		done
	done
done

echo "code succefully ran"


sleep 1
spd-say 'The simulation has ended!'

